version: 0.2.{build}.0
image: Visual Studio 2019

environment:
  VSTEST_LOGGER: Appveyor


install:
  - cmd: CALL build\SetEnv.bat
  - cmd: dotnet tool restore
  # CI specific installations
  - cmd: dotnet tool update Codecov.Tool --version 1.12.4
  - cmd: dotnet add Vigicrues.Tests\Vigicrues.Tests.csproj package Appveyor.TestLogger --version 2.0.0
cache:
  - .tmp -> appveyor.yml, global.json, build\versions.env



before_build:
  - cmd: SET PACKAGE_VERSION=%APPVEYOR_BUILD_VERSION%

build_script:
  - cmd: dotnet msbuild Vigicrues.Client.proj /nologo /t:UpdateVersion;Release /m /r /l:"C:\Program Files\AppVeyor\BuildAgent\dotnetcore\Appveyor.MSBuildLogger.dll" /fl /flp:logfile=build.log;verbosity=diagnostic;encoding=UTF-8 /nr:False /v:normal



artifacts:
  - path: tmp\out\bin\*.nupkg
  - path: tmp\*results.xml
  - path: build.log



deploy:
  - provider: NuGet
    server: https://www.myget.org/F/mcartoixa/api/v2/package
    api_key:
      secure: Iu8h9DYVcJWywLWAQowayV8lQzzU31p9SPyrTY7ItGxbciykN9Wy2AxuU3FE0RXT
    artifact: /.*\.nupkg/
    skip_symbols: true
    on:
      branch: main
  - provider: GitHub
    auth_token:
      secure: EGY6f1dfY5J0ivpjEapNo9BMNUGXx+FhJ7TG7HI3LypJZ5WlrTP2fEm+QV5j6HHW
    description: ''
    artifact: /.*/
    draft: true
    on:
      branch: main
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: TPglWbZZpZtWIcpUNxT8Ee9Yw9W0Shh22b2GZfdMN9cyM6rZZn+8b9qKh0KHIuwK
    artifact: /.*\.nupkg/
    skip_symbols: true
    on:
      branch: main
      appveyor_repo_tag: true



on_success:
  - cmd: dotnet tool run codecov -f "tmp\*-cobertura-results.xml"


on_failure:
  - ps: Push-AppveyorArtifact build.log
