//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vigicrues.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HttpResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HttpResponses() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vigicrues.Resources.HttpResponses", typeof(HttpResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;@context&quot;: {
        ///        &quot;mat&quot;: &quot;http://id.eaufrance.fr/ddd/mat/3.1/&quot;,
        ///        &quot;int&quot;: &quot;http://id.eaufrance.fr/ddd/int/2/&quot;,
        ///        &quot;vic&quot;: &quot;http://id.eaufrance.fr/ddd/vic/1.1/&quot;,
        ///        &quot;com&quot;: &quot;http://id.eaufrance.fr/ddd/com/4/&quot;,
        ///        &quot;hyd&quot;: &quot;http://id.eaufrance.fr/ddd/hyd/2.3/&quot;,
        ///        &quot;eth&quot;: &quot;http://id.eaufrance.fr/ddd/eth/2/&quot;,
        ///        &quot;zon&quot;: &quot;http://id.eaufrance.fr/ddd/zon/2.2/&quot;,
        ///        &quot;mdo&quot;: &quot;http://id.eaufrance.fr/ddd/mdo/1.4/&quot;
        ///    },
        ///    &quot;mat:Scenario&quot;: {
        ///        &quot;Flux&quot;: {
        ///        [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string InfoVigiCru_CdEntVigiCru1 {
            get {
                return ResourceManager.GetString("InfoVigiCru_CdEntVigiCru1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;@context&quot;: {
        ///        &quot;mat&quot;: &quot;http://id.eaufrance.fr/ddd/mat/3.1/&quot;,
        ///        &quot;int&quot;: &quot;http://id.eaufrance.fr/ddd/int/2/&quot;,
        ///        &quot;vic&quot;: &quot;http://id.eaufrance.fr/ddd/vic/1.1/&quot;,
        ///        &quot;com&quot;: &quot;http://id.eaufrance.fr/ddd/com/4/&quot;,
        ///        &quot;hyd&quot;: &quot;http://id.eaufrance.fr/ddd/hyd/2.3/&quot;,
        ///        &quot;eth&quot;: &quot;http://id.eaufrance.fr/ddd/eth/2/&quot;,
        ///        &quot;zon&quot;: &quot;http://id.eaufrance.fr/ddd/zon/2.2/&quot;,
        ///        &quot;mdo&quot;: &quot;http://id.eaufrance.fr/ddd/mdo/1.4/&quot;
        ///    },
        ///    &quot;mat:Scenario&quot;: {
        ///        &quot;Flux&quot;: {
        ///        [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string InfoVigiCru_CdEntVigiCru1_detail {
            get {
                return ResourceManager.GetString("InfoVigiCru_CdEntVigiCru1_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;@context&quot;: {
        ///        &quot;mat&quot;: &quot;http://id.eaufrance.fr/ddd/mat/3.1/&quot;,
        ///        &quot;int&quot;: &quot;http://id.eaufrance.fr/ddd/int/2/&quot;,
        ///        &quot;vic&quot;: &quot;http://id.eaufrance.fr/ddd/vic/1.1/&quot;,
        ///        &quot;com&quot;: &quot;http://id.eaufrance.fr/ddd/com/4/&quot;,
        ///        &quot;hyd&quot;: &quot;http://id.eaufrance.fr/ddd/hyd/2.3/&quot;,
        ///        &quot;eth&quot;: &quot;http://id.eaufrance.fr/ddd/eth/2/&quot;,
        ///        &quot;zon&quot;: &quot;http://id.eaufrance.fr/ddd/zon/2.2/&quot;,
        ///        &quot;mdo&quot;: &quot;http://id.eaufrance.fr/ddd/mdo/1.4/&quot;
        ///    },
        ///    &quot;mat:Scenario&quot;: {
        ///        &quot;Flux&quot;: {
        ///        [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string InfoVigiCru_CdEntVigiCruAP1 {
            get {
                return ResourceManager.GetString("InfoVigiCru_CdEntVigiCruAP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;@context&quot;: {
        ///        &quot;mat&quot;: &quot;http://id.eaufrance.fr/ddd/mat/3.1/&quot;,
        ///        &quot;int&quot;: &quot;http://id.eaufrance.fr/ddd/int/2/&quot;,
        ///        &quot;vic&quot;: &quot;http://id.eaufrance.fr/ddd/vic/1.1/&quot;,
        ///        &quot;com&quot;: &quot;http://id.eaufrance.fr/ddd/com/4/&quot;,
        ///        &quot;hyd&quot;: &quot;http://id.eaufrance.fr/ddd/hyd/2.3/&quot;,
        ///        &quot;eth&quot;: &quot;http://id.eaufrance.fr/ddd/eth/2/&quot;,
        ///        &quot;zon&quot;: &quot;http://id.eaufrance.fr/ddd/zon/2.2/&quot;,
        ///        &quot;mdo&quot;: &quot;http://id.eaufrance.fr/ddd/mdo/1.4/&quot;
        ///    },
        ///    &quot;mat:Scenario&quot;: {
        ///        &quot;Flux&quot;: {
        ///        [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string InfoVigiCru_TypEntVigiCru2 {
            get {
                return ResourceManager.GetString("InfoVigiCru_TypEntVigiCru2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;@context&quot;: {
        ///        &quot;mat&quot;: &quot;http://id.eaufrance.fr/ddd/mat/3.1/&quot;,
        ///        &quot;int&quot;: &quot;http://id.eaufrance.fr/ddd/int/2/&quot;,
        ///        &quot;vic&quot;: &quot;http://id.eaufrance.fr/ddd/vic/1.1/&quot;,
        ///        &quot;com&quot;: &quot;http://id.eaufrance.fr/ddd/com/4/&quot;,
        ///        &quot;hyd&quot;: &quot;http://id.eaufrance.fr/ddd/hyd/2.3/&quot;,
        ///        &quot;eth&quot;: &quot;http://id.eaufrance.fr/ddd/eth/2/&quot;,
        ///        &quot;zon&quot;: &quot;http://id.eaufrance.fr/ddd/zon/2.2/&quot;,
        ///        &quot;mdo&quot;: &quot;http://id.eaufrance.fr/ddd/mdo/1.4/&quot;
        ///    },
        ///    &quot;mat:Scenario&quot;: {
        ///        &quot;Flux&quot;: {
        ///        [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string InfoVigiCru_TypEntVigiCru2_detail {
            get {
                return ResourceManager.GetString("InfoVigiCru_TypEntVigiCru2_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;@context&quot;: {
        ///        &quot;mat&quot;: &quot;http://id.eaufrance.fr/ddd/mat/3.1/&quot;,
        ///        &quot;int&quot;: &quot;http://id.eaufrance.fr/ddd/int/2/&quot;,
        ///        &quot;vic&quot;: &quot;http://id.eaufrance.fr/ddd/vic/1.1/&quot;,
        ///        &quot;com&quot;: &quot;http://id.eaufrance.fr/ddd/com/4/&quot;,
        ///        &quot;hyd&quot;: &quot;http://id.eaufrance.fr/ddd/hyd/2.3/&quot;,
        ///        &quot;eth&quot;: &quot;http://id.eaufrance.fr/ddd/eth/2/&quot;,
        ///        &quot;zon&quot;: &quot;http://id.eaufrance.fr/ddd/zon/2.2/&quot;,
        ///        &quot;mdo&quot;: &quot;http://id.eaufrance.fr/ddd/mdo/1.4/&quot;
        ///    },
        ///    &quot;mat:Scenario&quot;: {
        ///        &quot;Flux&quot;: {
        ///        [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string InfoVigiCru_TypEntVigiCru4 {
            get {
                return ResourceManager.GetString("InfoVigiCru_TypEntVigiCru4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;@context&quot;: {
        ///        &quot;mat&quot;: &quot;http://id.eaufrance.fr/ddd/mat/3.1/&quot;,
        ///        &quot;int&quot;: &quot;http://id.eaufrance.fr/ddd/int/2/&quot;,
        ///        &quot;vic&quot;: &quot;http://id.eaufrance.fr/ddd/vic/1.1/&quot;,
        ///        &quot;com&quot;: &quot;http://id.eaufrance.fr/ddd/com/4/&quot;,
        ///        &quot;hyd&quot;: &quot;http://id.eaufrance.fr/ddd/hyd/2.3/&quot;,
        ///        &quot;eth&quot;: &quot;http://id.eaufrance.fr/ddd/eth/2/&quot;,
        ///        &quot;zon&quot;: &quot;http://id.eaufrance.fr/ddd/zon/2.2/&quot;,
        ///        &quot;mdo&quot;: &quot;http://id.eaufrance.fr/ddd/mdo/1.4/&quot;
        ///    },
        ///    &quot;mat:Scenario&quot;: {
        ///        &quot;Flux&quot;: {
        ///        [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string StaEntVigiCru {
            get {
                return ResourceManager.GetString("StaEntVigiCru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;@context&quot;: {
        ///        &quot;mat&quot;: &quot;http://id.eaufrance.fr/ddd/mat/3.1/&quot;,
        ///        &quot;int&quot;: &quot;http://id.eaufrance.fr/ddd/int/2/&quot;,
        ///        &quot;vic&quot;: &quot;http://id.eaufrance.fr/ddd/vic/1.1/&quot;,
        ///        &quot;com&quot;: &quot;http://id.eaufrance.fr/ddd/com/4/&quot;,
        ///        &quot;hyd&quot;: &quot;http://id.eaufrance.fr/ddd/hyd/2.3/&quot;,
        ///        &quot;eth&quot;: &quot;http://id.eaufrance.fr/ddd/eth/2/&quot;,
        ///        &quot;zon&quot;: &quot;http://id.eaufrance.fr/ddd/zon/2.2/&quot;,
        ///        &quot;mdo&quot;: &quot;http://id.eaufrance.fr/ddd/mdo/1.4/&quot;
        ///    },
        ///    &quot;mat:Scenario&quot;: {
        ///        &quot;Flux&quot;: {
        ///        [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string StaEntVigiCru_CdEntVigiCru1 {
            get {
                return ResourceManager.GetString("StaEntVigiCru_CdEntVigiCru1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;@context&quot;: {
        ///        &quot;mat&quot;: &quot;http://id.eaufrance.fr/ddd/mat/3.1/&quot;,
        ///        &quot;int&quot;: &quot;http://id.eaufrance.fr/ddd/int/2/&quot;,
        ///        &quot;vic&quot;: &quot;http://id.eaufrance.fr/ddd/vic/1.1/&quot;,
        ///        &quot;com&quot;: &quot;http://id.eaufrance.fr/ddd/com/4/&quot;,
        ///        &quot;hyd&quot;: &quot;http://id.eaufrance.fr/ddd/hyd/2.3/&quot;,
        ///        &quot;eth&quot;: &quot;http://id.eaufrance.fr/ddd/eth/2/&quot;,
        ///        &quot;zon&quot;: &quot;http://id.eaufrance.fr/ddd/zon/2.2/&quot;,
        ///        &quot;mdo&quot;: &quot;http://id.eaufrance.fr/ddd/mdo/1.4/&quot;
        ///    },
        ///    &quot;mat:Scenario&quot;: {
        ///        &quot;Flux&quot;: {
        ///        [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string StaEntVigiCru_CdEntVigiCruE351122001 {
            get {
                return ResourceManager.GetString("StaEntVigiCru_CdEntVigiCruE351122001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;@context&quot;: {
        ///        &quot;mat&quot;: &quot;http://id.eaufrance.fr/ddd/mat/3.1/&quot;,
        ///        &quot;int&quot;: &quot;http://id.eaufrance.fr/ddd/int/2/&quot;,
        ///        &quot;vic&quot;: &quot;http://id.eaufrance.fr/ddd/vic/1.1/&quot;,
        ///        &quot;com&quot;: &quot;http://id.eaufrance.fr/ddd/com/4/&quot;,
        ///        &quot;hyd&quot;: &quot;http://id.eaufrance.fr/ddd/hyd/2.3/&quot;,
        ///        &quot;eth&quot;: &quot;http://id.eaufrance.fr/ddd/eth/2/&quot;,
        ///        &quot;zon&quot;: &quot;http://id.eaufrance.fr/ddd/zon/2.2/&quot;,
        ///        &quot;mdo&quot;: &quot;http://id.eaufrance.fr/ddd/mdo/1.4/&quot;
        ///    },
        ///    &quot;mat:Scenario&quot;: {
        ///        &quot;Flux&quot;: {
        ///        [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TerEntVigiCru {
            get {
                return ResourceManager.GetString("TerEntVigiCru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;@context&quot;: {
        ///        &quot;mat&quot;: &quot;http://id.eaufrance.fr/ddd/mat/3.1/&quot;,
        ///        &quot;int&quot;: &quot;http://id.eaufrance.fr/ddd/int/2/&quot;,
        ///        &quot;vic&quot;: &quot;http://id.eaufrance.fr/ddd/vic/1.1/&quot;,
        ///        &quot;com&quot;: &quot;http://id.eaufrance.fr/ddd/com/4/&quot;,
        ///        &quot;hyd&quot;: &quot;http://id.eaufrance.fr/ddd/hyd/2.3/&quot;,
        ///        &quot;eth&quot;: &quot;http://id.eaufrance.fr/ddd/eth/2/&quot;,
        ///        &quot;zon&quot;: &quot;http://id.eaufrance.fr/ddd/zon/2.2/&quot;,
        ///        &quot;mdo&quot;: &quot;http://id.eaufrance.fr/ddd/mdo/1.4/&quot;
        ///    },
        ///    &quot;mat:Scenario&quot;: {
        ///        &quot;Flux&quot;: {
        ///        [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TerEntVigiCru_CdEntVigiCru25 {
            get {
                return ResourceManager.GetString("TerEntVigiCru_CdEntVigiCru25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;@context&quot;: {
        ///        &quot;mat&quot;: &quot;http://id.eaufrance.fr/ddd/mat/3.1/&quot;,
        ///        &quot;int&quot;: &quot;http://id.eaufrance.fr/ddd/int/2/&quot;,
        ///        &quot;vic&quot;: &quot;http://id.eaufrance.fr/ddd/vic/1.1/&quot;,
        ///        &quot;com&quot;: &quot;http://id.eaufrance.fr/ddd/com/4/&quot;,
        ///        &quot;hyd&quot;: &quot;http://id.eaufrance.fr/ddd/hyd/2.3/&quot;,
        ///        &quot;eth&quot;: &quot;http://id.eaufrance.fr/ddd/eth/2/&quot;,
        ///        &quot;zon&quot;: &quot;http://id.eaufrance.fr/ddd/zon/2.2/&quot;,
        ///        &quot;mdo&quot;: &quot;http://id.eaufrance.fr/ddd/mdo/1.4/&quot;
        ///    },
        ///    &quot;mat:Scenario&quot;: {
        ///        &quot;Flux&quot;: {
        ///        [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TronEntVigiCru {
            get {
                return ResourceManager.GetString("TronEntVigiCru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;@context&quot;: {
        ///        &quot;mat&quot;: &quot;http://id.eaufrance.fr/ddd/mat/3.1/&quot;,
        ///        &quot;int&quot;: &quot;http://id.eaufrance.fr/ddd/int/2/&quot;,
        ///        &quot;vic&quot;: &quot;http://id.eaufrance.fr/ddd/vic/1.1/&quot;,
        ///        &quot;com&quot;: &quot;http://id.eaufrance.fr/ddd/com/4/&quot;,
        ///        &quot;hyd&quot;: &quot;http://id.eaufrance.fr/ddd/hyd/2.3/&quot;,
        ///        &quot;eth&quot;: &quot;http://id.eaufrance.fr/ddd/eth/2/&quot;,
        ///        &quot;zon&quot;: &quot;http://id.eaufrance.fr/ddd/zon/2.2/&quot;,
        ///        &quot;mdo&quot;: &quot;http://id.eaufrance.fr/ddd/mdo/1.4/&quot;
        ///    },
        ///    &quot;mat:Scenario&quot;: {
        ///        &quot;Flux&quot;: {
        ///        [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TronEntVigiCru_CdEntVigiCruAP1 {
            get {
                return ResourceManager.GetString("TronEntVigiCru_CdEntVigiCruAP1", resourceCulture);
            }
        }
    }
}
